### ISSUE TITLE
Publish to NuGet?

### ISSUE THREAD

**Issue by nblumhardt** [michaelnoonan/Auth0-Owin-JwtBearerAuthentication#2]
Greetings Mike :-)

Any clues into where this repo is headed, i.e. do you intend to maintain it and publish a package to NuGet, or is it a point-in-time thing you're happy to leave in its current state?

Will offer any help here that we can.

Cheers!

**Comment by michaelnoonan** [comment]
Long time! ;)

It was point in time for a couple of projects because Auth0 didn't have an
answer to this problem. I offered the repo to them and haven't heard since.
I wonder if it's worth migrating over to
https://github.com/auth0/auth0-aspnet-owin?

Mike

**Comment by nblumhardt** [comment]
Thanks Mike, we'll mull that over. Appreciate the pointer!
